### ISSUE TITLE
How to solve the ssl.SSLEOFError?

### ISSUE THREAD

**Issue by 985zhangguoxu** [YaN9-Y/D4#6]
Dear author:
    I am a student from China. I just only use the pretrained model to test the D4. When I enter the command" python3 test.py --model 1 --checkpoints ./D4-main/checkpoints/quick", The following prompt appears on the screen:

Downloading: "https://github.com/rwightman/gen-efficientnet-pytorch/archive/master.zip" to /home/ubuntu/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/home/ubuntu/anaconda3/envs/D4/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1045)

Thank you for help how to solve it?_

**Comment by YaN9-Y** [comment]
Such errors may be related to your internet connection.  A VPN may help I guess? I am not sure.
